AWSTemplateFormatVersion: '2010-09-09'
Description: New Role

Resources:
  MyIAMRole:
    Type: 'AWS::IAM::Role'
    Properties: 
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'ec2.amazonaws.com'   # This role will be assumed by EC2 instances
            Action: 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: 'MyEC2Policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:ListBucket'
                  - 's3:PutObject'
                  - 's3:GetObject'
                Resource: '*'
